name               = "carbon-calculator"
main               = "functions/_worker.ts"
compatibility_date = "2025-05-09"
workers_dev        = true

# Statische Dateien liegen in public/
assets = { directory = "./public" }
